# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM --platform=$TARGETPLATFORM docker.io/bitnami/minideb:bookworm AS build
#FROM --platform=$TARGETPLATFORM centos:centos7.9.2009 AS build
ARG VERSION=3.0.11
ARG TARGETPLATFORM
WORKDIR /usr/local
COPY dist/loongcollector-${VERSION}.linux-*.tar.gz .
RUN tar -xzf loongcollector-${VERSION}.linux-${TARGETPLATFORM##*/}.tar.gz


FROM docker.io/bitnami/minideb:bookworm
SHELL ["/bin/bash", "-c"]
ENV container docker

ARG HOST_OS=Linux
ARG VERSION=3.0.11
ARG TARGETPLATFORM

RUN mkdir -p /usr/local/loongcollector/{conf/instance_config/local,log,data/checkpoint,run}

COPY --from=build --chmod=755 /usr/local/loongcollector-${VERSION} /usr/local/loongcollector

WORKDIR /usr/local/loongcollector

COPY example_config/start_with_docker/loongcollector_config.json /usr/local/loongcollector/conf/instance_config/local/loongcollector_config.json
COPY scripts/loongcollector_control.sh /usr/local/loongcollector/

ENV HTTP_PROBE_PORT=7953 \
    ALIYUN_LOGTAIL_USER_DEFINED_ID=default \
    docker_file_cache_path=checkpoint/docker_path_config.json
CMD ["/usr/local/loongcollector/loongcollector_control.sh", "start_and_block"]
